# Generated by Django 4.2.11 on 2024-04-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="barcode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="part",
            name="serial_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
