# Generated by Django 4.2.11 on 2024-04-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0002_part_barcode_part_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="barcode",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="part",
            name="serial_number",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
