# Generated by Django 4.2.11 on 2024-04-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0003_alter_part_barcode_alter_part_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes"),
        ),
    ]
