# Generated by Django 4.2.11 on 2024-04-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_alter_location_address"),
        ("parts", "0004_part_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="part_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part_locations",
                to="locations.location",
            ),
        ),
    ]
