# Generated by Django 4.2.11 on 2024-04-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("color", models.CharField(max_length=50)),
                ("vin", models.CharField(max_length=17, unique=True)),
                ("mileage", models.IntegerField()),
                ("fuel_type", models.CharField(max_length=50)),
                ("transmission", models.CharField(max_length=50)),
                ("engine_size", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
